cdk/lib/__snapshots__/cdk-playground.test.ts.snap
cdk/lib/cdk-playground.ts
cdk/package-lock.json
cdk/package.json

Upgrades `@guardian/cdk` to `14.4.1`, primarily to take advantage of the access changes introduced in https://github.com/guardian/cdk/pull/500 and https://github.com/guardian/cdk/pull/534.
As this is a test project, I've already made these infrastructure changes via CFN. Note that I deleted the old stack and created a new one; moving from an internal -> internet-facing scheme is a destructive operation and this was the fastest way to do it for testing purposes. I've manually updated the DNS record too.
* We are using the latest version of `@guardian/cdk`
* The stack is actually publicly accessible (it seems that this didn't work properly on `14.2.0` as the load balancer was `internal`)

chore: upgrade @guardian/cdk to 14.4.1

---

.github/workflows/ci.yaml
README.md
build.sbt
project/plugins.sbt
script/ci

Moves CI to GitHub Actions with the help of https://github.com/guardian/actions-assume-aws-role.
Here's a table of reasons:
| GitHub Actions                                                                     | TeamCity                                                                                                         |
|------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------|
| ✅ Build configuration is entirely tracked in VCS                                   | ❌ Build configuration is mostly done through UI                                                                  |
| ✅ No build queue …

chore: Switch to GHA for CI 🎉 

---

cdk/lib/__snapshots__/cdk-playground.test.ts.snap
cdk/lib/cdk-playground.ts

We want a Graviton instance - use a `t4g.micro` instance.
The change in #113 was faulty - I used the same instance type that was in the snapshot, which was the default of a parameter rather than an actual value. The actual value used in the deployed stack is `t4g.micro`.
This change also down-scales our ASG to run 1 instance in PROD as cdk-playground isn't a production app.

fix: Use correct instance type

---

build.sbt
project/build.properties

Upgrades the `sbt` [version](https://github.com/sbt/sbt/releases/tag/v1.5.6) to include a patch for [Remote code injection in Log4j](https://github.com/advisories/GHSA-jfh8-c2jp-5v3q).

Use sbt version 1.5.6

---

.github/workflows/ci.yaml

We developed https://github.com/guardian/actions-assume-aws-role to support the migration to GitHub Actions (more specifically, it allowed us to upload build artifacts to Riff-Raff's S3 buckets without using permanent credentials).
There is now an official action (maintained by AWS) which offers this functionality - https://github.com/aws-actions/configure-aws-credentials. This PR switches to using the AWS alternative instead of the (now deprecated) Guardian action. 
Related PRs:
https://github.com/guardian/actions-assume-aws-role/pull/80
https://github.com/guardian/node-riffraff-artifact/pull/33
https://github.com/guardian/sbt-riffraff-artifact/pull/69

Use aws-actions/configure-aws-credentials instead of guardian/actions-assume-aws-role

---

CODEOWNERS

Uses a more specific team for CODEOWNERS to direct reviews to the appropriate place

Update CODEOWNERS to Ops team

---

app/AppComponents.scala
app/AppLoader.scala
app/RequestLoggingFilter.scala
app/controllers/ManagementController.scala
build.sbt
cdk/lib/__snapshots__/cdk-playground.test.ts.snap
cdk/lib/cdk-playground.ts
cdk/package-lock.json
cdk/package.json
conf/logback.xml
project/build.properties
project/plugins.sbt

Easiest reviewed commit by commit.
In this change we configure application log shipping to Central ELK using https://github.com/guardian/devx-logs 🎉 .
There are a couple of prerequisites to enable this:
-  `@guardian/cdk` must be on v41.1.0 ([release notes](https://github.com/guardian/cdk/releases/tag/v41.1.0))
- The ASG must have a `SystemdUnit` tag (to be done by GuCDK in future, as described [here](https://github.com/guardian/amiable/pull/127))
`cdk-playground` doesn't actually produce any logs, so in this change a request logging filter has been added (https://github.com/guardian/cdk-playground/pull/198/commits/56e6daa575ec16ab83fc90c78e3ac4cd4c28947b).
It's worth noting that logging was not [configured correctly](https://www.playframework.com/documentation/2.8.x/SettingsLogger#Using-a …

Ship logs to Central ELK

---

cdk/package-lock.json
cdk/package.json

- `@guardian/cdk` from 41.1.0 to 45.0.0
- `aws-cdk` from 2.20.0 to 2.25.0
- `aws-cdk-lib` from 2.20.0 to 2.25.0
- `constructs` from 10.0.110 to 10.1.17
- `@types/jest` from 27.4.1 to 27.5.1
- `@types/node` from 17.0.31 to 17.0.35
- `eslint` from 8.14.0 to 8.16.0
- `jest` from 27.5.1 to 28.1.0
- `ts-jest` from 27.1.4 to 28.0.3
- `ts-node` from 10.7.0 to 10.8.0
Closes #202 ,#205, #208, #209, #210.

chore(deps): Bumps various dependencies in `cdk`

---

riff-raff.yaml

[We only deploy this project to `PROD`.](https://riffraff.gutools.co.uk/deployment/history?projectName=devx%3A%3Acdk-playground&page=1)

Add PROD as the only allowed stage

---

.github/workflows/ci.yaml
build.sbt
project/plugins.sbt
script/ci

Switches to using `guardian/actions-riff-raff`, testing https://github.com/guardian/actions-riff-raff/pull/18. This allows us to remove the `sbt-riffraff-artifact` plugin, making our application code ignorant of Riff-Raff settings - these are pushed to CI.
We should be able to deploy as normal.

ci: Switch to guardian/actions-riff-raff

---

cdk/lib/cdk-playground.test.ts

It's no longer necessary, as GuCDK itself is already well tested.

test: Remove test of riff-raff.yaml generation

---

cdk/lib/cdk-playground.ts

The previous recipe was designed to be used by DevX services, and thus any changes with it might not have been tested on this service.
We've now got a dedicated recipe, which includes:
- Ubuntu Jammy
- Java 11 Corretto
- CDK Base
Deploy it, it should succeed.

chore: Use updated AMIgo recipe

---

.github/workflows/ci.yaml

`aws-actions/configure-aws-credentials` v2 moves to Node 16, resolving a [deprecation warning](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).

chore(deps): Update `aws-actions/configure-aws-credentials` to v2

---

.github/workflows/ci.yaml

Update the version of Java used in CI to match that used in PROD (Java 11, corretto). Also cache sbt dependencies to improve build time.

ci: Correct Java setup

---

cdk/package-lock.json
cdk/package.json

Updates GuCDK to [49.4.1](https://github.com/guardian/cdk/releases/tag/v49.4.1).

chore(deps): Bump @guardian/cdk from 49.4.0 to 49.4.1

---

build.sbt
project/plugins.sbt

Fixes all high level vulnerabilities. simplifies build.sbt. bumps scala version. I'm also adding this to [scala-steward](https://github.com/guardian/scala-steward-public-repos/pull/37)
run against snyk, confirm build still passes
confirm there are no more high level vulnerabilities

version bumps, remove libraries updated transitively

---

.github/workflows/snyk.yml

If someone forks/copies this repo and runs the action, it will try to send the output to devx's snyk org. We don't want that to happen. Send it to the test org instead.

send report to guardian-test in case someone runs the action

---

build.sbt

Bumps logback-classic to 1.2.13. Resolving 4 high vulnerabilities.

Bump logback-classic to 1.2.13

---

.github/workflows/dependabot-auto-approve.yml

Add workflow to approve Dependabot PRs, using [GitHub's example](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#approve-a-pull-request).

feat(deps): Auto approve Dependabot PRs

---

cdk/lib/__snapshots__/cdk-playground.test.ts.snap
cdk/lib/cdk-playground.ts

This is a cleanup PR.
This PR reverses the change made in https://github.com/guardian/cdk-playground/pull/462, removing the domain and GuCname added in that PR for use in a Fastly DR test we were conducting. 
Those additions were simply to provide something to point to from Fastly and made no difference to the real functioning of the cdk-playground.
No testing needed
It will not be possible to reach cdk-playground.gutools.co.uk by hitting cdk-status-resources.guardianapis.com.
No risks.

Remove domain and GuCname used for Fastly DR testing

---

cdk/lib/__snapshots__/cdk-playground.test.ts.snap
cdk/lib/cdk-playground.ts

Similar to https://github.com/guardian/cdk-playground/pull/462.
I want to put a Fastly service in front of this app to simplify/de-risk the testing for [this card](https://trello.com/c/JKlLGC8b/2744-spike-determine-how-to-get-fastly-metrics-into-cloudwatch).
I will revert this PR when the testing is complete.

Configure DNS for test Fastly service

---

cdk/lib/__snapshots__/cdk-playground.test.ts.snap
cdk/lib/cdk-playground.ts

Follow up to https://github.com/guardian/cdk-playground/pull/479. 
`gutools.co.uk` was a bad choice of domain name because our Fastly certificate does not include `*gutools.co.uk` as a subject alt name. `*.code.dev-guardianapis.com` is listed as a subject alt name, so let's use that domain instead[^1].
[^1]: We're just using this for testing, so the domain name doesn't really matter.

Modify Fastly DNS name to resolve certificate problem

---

cdk/lib/__snapshots__/cdk-playground.test.ts.snap
cdk/lib/cdk-playground.ts

This PR builds upon https://github.com/guardian/cdk-playground/pull/479 and https://github.com/guardian/cdk-playground/pull/480.
Now that we are using Fastly to route requests to this application, we can enable [log streaming](https://docs.fastly.com/en/guides/about-fastlys-realtime-log-streaming-features) via the Fastly service. In order to do this, [we need to give Fastly permissions to push log files into our S3 bucket](https://docs.fastly.com/en/guides/log-streaming-amazon-s3#adding-amazon-s3-as-a-logging-endpoint), so this PR uses GuCDK constructs to create an appropriate IAM role.
The ARN of the IAM role that we create here (and the name of the bucket, which is created by https://github.com/guardian/fastly-logs-to-metrics) has already been wired up to the service's logging …

Provision a role for Fastly log shipping

---

app/controllers/ManagementController.scala
conf/routes

This allows us to more easily test functionality that depends on specific status codes being served (e.g. alarms, metric collection and dashboards).

Add some new routes for response code testing

---

cdk/bin/cdk.ts
cdk/cdk.json

Set the CloudFormation stack name, and AWS profile to enable `npm run diff` to work.

Fix `npm run diff` script

---

cdk/package-lock.json
cdk/package.json

Update GuCDK version. Release notes here - https://github.com/guardian/cdk/releases/tag/v59.2.4.

chore(deps): Update GuCDK from 59.2.3 to 59.2.4

---

cdk/jest.setup.js
cdk/lib/__snapshots__/cdk-playground.test.ts.snap
cdk/lib/cdk-playground.ts

Adds two new tags to the ASG:
- `gu:build:number`
- `gu:build:sha`
These values are also added as stack metadata. The tags are not added to all resources to reduce noise in the CloudFormation logs.
This makes the changes in #512 more useful, and potentially paves the way to remove the [`sbt-buildinfo` plugin](https://github.com/guardian/cdk-playground/blob/264e42d6540d11cf34d6d0c6a67e3a56565f6c5e/build.sbt#L44-L60).

feat: Add build info as stack metadata and ASG tags

---

.github/workflows/ci.yaml
.gitignore
cdk/lib/__snapshots__/cdk-playground.test.ts.snap
cdk/lib/cdk-playground.ts
script/ci

Uses the new `GuEc2AppExperimental` available in [GuCDK v59.5.0](https://github.com/guardian/cdk/releases/tag/v59.5.0).
This formalises the changes of https://github.com/guardian/cdk-playground/pull/522, installing the experimental pattern from an NPM release.
N/A as testing has been performed in https://github.com/guardian/cdk-playground/pull/522.

feat: Use `GuEc2AppExperimental` to perform EC2 deployments via CloudFormation

---

cdk/lib/__snapshots__/cdk-playground.test.ts.snap
cdk/package-lock.json
cdk/package.json

Update the version of GuCDK. This should improve the stability of deployments. See https://github.com/guardian/cdk/pull/2462.

chore(deps-dev): Update GuCDK from 59.5.0 to 59.5.1

---

cdk/bin/cdk.ts
cdk/jest.setup.js
cdk/lib/__snapshots__/cdk-playground.test.ts.snap
cdk/lib/cdk-playground.test.ts
cdk/lib/cdk-playground.ts

Reverts #513 and removes the need to use a Jest mock.

Pass build identifier as prop

---

cdk/lib/__snapshots__/cdk-playground.test.ts.snap
cdk/lib/cdk-playground.ts

Reverts guardian/cdk-playground#532 as the demo for Engineering All Hands has finished now. Revert back to one instance to save on costs.

Revert "Update capacity to be more production-like"

---

README.md
cdk/lib/__snapshots__/cdk-playground.test.ts.snap
cdk/lib/cdk-playground.ts
script/scale-in
script/scale-out

Add some simple scaling policies to the autoscaling group. This allows us to use the [AWS CLI](https://docs.aws.amazon.com/cli/latest/reference/autoscaling/execute-policy.html) to programatically trigger a scale in/out event.
Using simple scaling, over target tracking scaling, makes it easier to test certain deployment situations,
as scaling events become somewhat deterministic.
```console
❯ ./script/scale-out
Desired capacity has been updated from 1 to 2
❯ ./script/scale-in 
Desired capacity has been updated from 2 to 1
```

feat: Add scripts to trigger ASG scale in/out events

---

.github/workflows/ci.yaml
.tool-versions

Inspired by https://github.com/guardian/amigo/pull/1587, this change uses the shared action to setup SBT for CI. These changes bring this repository inline with others in the organisaion.
This should resolve the slow (multi hour!) builds seen on https://github.com/guardian/cdk-playground/pull/670, which appears to be related to https://github.com/actions/runner-images/issues/11988.

ci: Use `ubuntu-latest` runner and `guardian/setup-scala@v1`

---

cdk/lib/__snapshots__/cdk-playground.test.ts.snap
cdk/lib/cdk-playground.ts

Enables ALB access logging, writing to a new S3 bucket specifically for this application. This is to aid testing the ingestion of ALB logs into the Availability Dashboard. This work is currently a spike, hence the bucket's deletion policy. If/when the spike proves successful, we'll need to think about the S3 bucket more carefully - do we have a single organisational bucket, or one per account, or one per service, etc?

feat: Enable ALB access logging

---

cdk/lib/__snapshots__/cdk-playground.test.ts.snap
cdk/lib/cdk-playground.ts

Updates the changes in https://github.com/guardian/cdk-playground/pull/721 following https://github.com/guardian/aws-account-setup/pull/345 which created an org-wide S3 bucket.
> [!NOTE]
> This change removes an S3 bucket, therefore would need to be deployed "dangerously" in Riff-Raff.

feat: Ship access logs to newly created org-wide S3 bucket

---

cdk/bin/cdk.ts
cdk/cdk.json
cdk/event-forwarder/.env
cdk/event-forwarder/index.ts
cdk/lib/__snapshots__/cdk-playground.test.ts.snap
cdk/lib/__snapshots__/event-forwarder.test.ts.snap
cdk/lib/cdk-playground.ts
cdk/lib/event-forwarder.ts
script/scale-in
script/scale-out

The playground isn't suited for long-lived projects, which this is. Switch to the deployTools account as DevX own this service. To achieve this, the `stack` value switches from `playground` to `deploy`.
The domain name (`cdk-playground.gutools.co.uk`) isn't being updated, therefore to deploy:
I don't think it's possible to test this it requires removing and recreating infrastructure.
Ultimately `cdk-playground.gutools.co.uk` still returns content. Indeed https://cdk-playground.gutools.co.uk/tags should show the `Stack` tag having value `deploy`.
At a DNS level the CNAME should point to a new location. Currently, it is this:
```console
❯ dig +short cdk-playground.gutools.co.uk
playg-loadb-eieho3l6xpad-1330756013.eu-west-1.elb.amazonaws.com.
```
There isn't any. This app is for the DevX …

feat: Move infrastructure from playground account to deployTools account

---

.github/workflows/ci.yaml
cdk/bin/cdk.ts
cdk/lib/__snapshots__/cdk-playground.test.ts.snap
cdk/lib/__snapshots__/event-forwarder.test.ts.snap
cdk/lib/cdk-playground.test.ts
cdk/lib/cdk-playground.ts
cdk/lib/event-forwarder.test.ts
cdk/lib/event-forwarder.ts

Create a CODE stage as a pre-cursor to deleting the PROD stage.
This application is a testing ground used by DevX to confirm behaviour of [GuCDK](https://github.com/guardian/cdk) code changes on real infrastructure. Consequently, this application doesn't follow the usual conventions, for example only deploying `main` to PROD.
Deploying is the best test here. I've successfully [deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/a111c345-da49-419e-8d75-90d9b797723a). Consequently https://cdk-playground.code.dev-gutools.co.uk/tags exists.

feat(cdk): Create a CODE stage

---

README.md

We no longer have a PROD stage, only CODE. See also #771.

docs: Update Riff-Raff URL

---

cdk/lib/__snapshots__/event-forwarder.test.ts.snap
cdk/lib/event-forwarder.ts
script/scale-in
script/scale-out

Updates the event filter to use the CODE stack in the deployTools account following the changes in:
- https://github.com/guardian/cdk-playground/pull/769
- https://github.com/guardian/cdk-playground/pull/770
- https://github.com/guardian/cdk-playground/pull/771
The last two panels on [this dashboard](https://metrics.gutools.co.uk/d/adyqx5hf3w1s0e/cdk-playground-deployment-dashboard?orgId=1&from=now-6h&to=now&timezone=browser) should populate.

fix(event-forwarder): Update event filter
